### ISSUE TITLE
Tests are not Coherent with Package Structure

### ISSUE THREAD

**Issue by manoskary** [CPJKU/partitura#165]
Some tests were created for sparts of pparts but now they do not look coherent with Performance and Score objects.

A double-proofing of the tests with minor corrections would be recommended at that point.

**Comment by neosatrapahereje** [comment]
The main goals for this issue are 

1. Use the `parts` attribute of `Score` and `Performance` objects in tests loading files with multiple parts instead of using the `iter_parts` method (which is called internally when creating  `Score` and `Performance` objects)
2. Rename variable names in the tests to reflect whether the variable is a `Score` or `Performance` (i.e., for now there are many `part` variables that are actually `Score` instances)

**Comment by manoskary** [comment]
Keeping this open is this still current?

**Comment by neosatrapahereje** [comment]
This is less of a technical issue and more of a stylistic one. It would be nice to be consistent in the tests, but at the same time, I don't really have much time to do this in the coming months. Since this is kind of similar to the issue about documentation, I would suggest to close it.
