### ISSUE TITLE
Bug with to_mached_score

### ISSUE THREAD

**Issue by manoskary** [CPJKU/partitura#200]
Error with match score `Schubert_D783_no15_p07.match` from Vienna 4x22.
The match score has an incorrect grouping of unique onsets when the function `pt.musicanalysis.encode_performance(score[0], perf[0], alignment, return_u_onset_idx=True)` is called. I think the problem is comming from the `to_mached_score` function located in `partitura.musicanalysis.performance_codec`, both the score and the alignment look fine. I couldn't find the where the error occurs.

To reproduce:

```python
import partitura as pt

matchfile = './OFAI-vienna4x22_rematched-7b60448/match/Schubert_D783_no15_p07.match'
score_fn = './OFAI-vienna4x22_rematched-7b60448/musicxml/Schubert_D783_no15.musicxml'


score = pt.load_musicxml(score_fn)
unique_onsets = pt.musicanalysis.performance_codec.get_unique_onset_idxs(score.note_array()["onset_div"])
perf, alignment = pt.load_match(matchfile)
performance_array, snotes, unique_onset_idx = pt.musicanalysis.encode_performance(score[0], perf[0], alignment, return_u_onset_idx=True)
if len(unique_onsets) > len(unique_onset_idx):
   raise ValueError()
```

**Comment by sildater** [comment]
Hey! The grouping is correct, the unique onsets are different because the one from the musicxml is just computing unique score positions over all existing score notes whereas the one from the alignment only takes into account the score positions at which a performed note exists. In this specific match file, the notes n143-1, n144-1, n84-2, n143-2, and n144-2 are deletions, so they get discarded in the performance codec (there's no performance to encode).
